fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    alternatives: "git://github.com/puppet-community/puppet-alternatives"
    hadoop: "git://github.com/MetaCenterCloudPuppet/cesnet-hadoop"
    hadoop_lib: "git://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib"
  symlinks:
    hbase: "#{source_dir}"
