name 'cesnet-hbase'
version '0.10.5'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hbase'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'HBase Cluster'
description 'HBase Cluster'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'cesnet/hadoop', '>= 0.9.4 <3.0.0'
dependency 'cesnet/hadoop_lib', '<1.0.0'
