name 'cesnet-hbase'
version '1.2.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hbase'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'HBase Cluster'
description 'HBase Cluster'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-hbase'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <7.0.0'
dependency 'cesnet/hadoop', '>= 0.9.4 <4.0.0'
dependency 'cesnet/hadoop_lib', '<1.0.0'
