name 'cesnet-hbase'
version '0.10.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hbase'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'HBase Cluster'
description 'HBase Cluster'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'adrien/alternatives', '>= 0.3.0 <1.0.0'
dependency 'cesnet/hadoop', '>= 0.9.4 <1.0.0'
